/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { initializeApp } from 'firebase/app';
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';
import { firebaseOptions } from './config/firebase-options';

declare let self: ServiceWorkerGlobalScope;

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Claim clients immediately
self.skipWaiting();
clientsClaim();

// Initialize Firebase using the shared options
const app = initializeApp(firebaseOptions);
const messaging = getMessaging(app);

onBackgroundMessage(messaging, (payload) => {
  console.debug('[sw.ts] Received background message:', payload);

  const notificationTitle = payload.notification?.title || 'fi-go';
  const notificationOptions = {
    body: payload.notification?.body || '',
    icon: '/icon-192x192.png',
    badge: '/icon-192x192.png',
    data: {
      ...payload.data,
      url: payload.fcmOptions?.link || self.registration.scope,
    },
  };

  self.registration.showNotification(notificationTitle, notificationOptions);
});

// Handle notification interaction
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  // Use self.registration.scope as fallback — '/' is relative and unreliable in SW context
  const url = event.notification.data?.url || self.registration.scope;

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Focus any existing PWA window rather than strict-URL matching.
      // On iOS, the open window's URL often has a trailing slash that differs
      // from the FCM link, so exact equality would always miss and open a second window.
      if (clientList.length > 0 && 'focus' in clientList[0]) {
        const existing = clientList[0] as WindowClient;
        existing.focus();
        // navigate() brings the existing window to the right URL without opening a new one
        if ('navigate' in existing) {
          return existing.navigate(url);
        }
        return;
      }
      return self.clients.openWindow(url);
    })
  );
});
