name: Deploy to Firebase Functions on merge
on:
  push:
    branches:
      - master
    paths:
      - 'projects/functions/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd projects/functions
          npm ci
      - name: Deploy to Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FI_GO_WEB }}
