name: Deploy to Firebase Functions
on:
  push:
    branches:
      - master
    paths:
      - 'projects/functions/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: projects/functions/package-lock.json
      - name: Install dependencies
        run: |
          cd projects/functions
          npm ci
      - name: Deploy to Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
